defmodule Librex.Repo.Migrations.CreateUniqueBookTitlePerAuthorIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:books, [:title, :author_id],
             name: "books_unique_book_title_per_author_index"
           )
  end

  def down do
    drop_if_exists unique_index(:books, [:title, :author_id],
                     name: "books_unique_book_title_per_author_index"
                   )
  end
end
