defmodule Librex.Repo.Migrations.CreateBooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:books, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :year_released, :bigint, null: false
      add :cover_image_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:authors,
            column: :id,
            name: "books_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:books, [:author_id])
  end

  def down do
    drop_if_exists index(:books, [:author_id])

    drop constraint(:books, "books_author_id_fkey")

    drop table(:books)
  end
end
