defmodule Librex.Repo.Migrations.ModifyReferenceForBookAuthorOnDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:books, "books_author_id_fkey")

    alter table(:books) do
      modify :author_id,
             references(:authors,
               column: :id,
               name: "books_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:books, "books_author_id_fkey")

    alter table(:books) do
      modify :author_id,
             references(:authors,
               column: :id,
               name: "books_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
